### ISSUE TITLE
优化注释样式

### ISSUE THREAD

**Issue by champkeh** [champkeh/wereadx#1]
参考[HTML 书籍注释信息样式](https://github.com/Sec-ant/weread-scraper/issues/30)

我觉得既然决定导出为html格式，那没有理由不使用js

**Comment by champkeh** [comment]
https://www.edrlab.org/open-standards/anatomy-of-an-epub-3-file/

epub格式似乎可以支持js，有空研究一下

**Comment by colin4k** [comment]
不需要 epub，可以参考https://github.com/leic4u/WeRead-Scraper，这个导出的html支持注释，然后用sigil导入html再导出的epub也直接支持注释

**Comment by ylqandy** [comment]
> 不需要 epub，可以参考[https://github.com/leic4u/WeRead-Scraper，这个导出的html支持注释，然后用sigil导入html再导出的epub也直接支持注释](https://github.com/leic4u/WeRead-Scraper%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%AF%BC%E5%87%BA%E7%9A%84html%E6%94%AF%E6%8C%81%E6%B3%A8%E9%87%8A%EF%BC%8C%E7%84%B6%E5%90%8E%E7%94%A8sigil%E5%AF%BC%E5%85%A5html%E5%86%8D%E5%AF%BC%E5%87%BA%E7%9A%84epub%E4%B9%9F%E7%9B%B4%E6%8E%A5%E6%94%AF%E6%8C%81%E6%B3%A8%E9%87%8A)

这个脚本我之前就在用了，但是原作者最近停止更新了，weread scraper的1.4.3抓取出来都是空白的，可惜。不知道其他人是不是也有这个问题。

**Comment by champkeh** [comment]
> 这个脚本我之前就在用了，但是原作者最近停止更新了，weread scraper的1.4.3抓取出来都是空白的，可惜。不知道其他人是不是也有这个问题。

我最上面那个issue就是指向他的那个仓库的，但不知道为啥关闭了

**Comment by colin4k** [comment]
貌似是被举报了，先是油猴里面下架，跟着脚本失效，不过我只是建议参考他对注释的处理

**Comment by champkeh** [comment]
@colin4k 已初步支持下载 epub 格式，欢迎测试与提交反馈

**Comment by champkeh** [comment]
@colin4k 关于epub的注释，你有没有一个例子，我参考下别人的epub文件里面注释都是怎么做的

**Comment by champkeh** [comment]
目前的注释效果还行，不需要使用js了，暂时就这样了

**Comment by colin4k** [comment]
> @colin4k 已初步支持下载 epub 格式，欢迎测试与提交反馈

感谢作者更新，试着导了本书，
链接：https://weread.qq.com/web/reader/f3c32820813ab7e9eg01071f?
弹出窗口报错："Failed to decode base64"
全书本来是26章，报错之后还是会下载下来，但只有11章

**Comment by champkeh** [comment]
> 弹出窗口报错："Failed to decode base64"

这个错误我看之前的日志也会时不时报一下，具体什么原因还没查清楚

> 全书本来是26章，报错之后还是会下载下来，但只有11章

报错之后会暂停下载，但是仍然会把已经下载好的那些章节拼起来导出
