### ISSUE TITLE
关于封号问题

### ISSUE THREAD

**Issue by bookoyo** [champkeh/wereadx#12]
账号被封一天，说违规爬虫，可能是今晚一次性下了10本的原因？

**Comment by champkeh** [comment]
还真会封号啊🤣

除了下载频繁，有没有开自动阅读？

**Comment by bookoyo** [comment]
> 还真会封号啊🤣
> 
> 除了下载频繁，有没有开自动阅读？

没开

**Comment by champkeh** [comment]
你 vid 方便发我一下嘛，我看下都下了哪些书

**Comment by champkeh** [comment]
https://github.com/champkeh/wereadx/blob/a0f15d6baad96916c1c91d5b4479b7eaa2a46f6c/src/frontend/apis/downloadSSE.ts#L36-L46

我看了下代码，目前每章之间的下载间隔是300毫秒，的确是有点小了，我先改成2秒吧，看下后续的情况。

但是这样会导致每本书的下载时间变长，但是这也是没办法的，毕竟客户端怎么做都不可能绕过服务器对请求频率的限制。

**Comment by champkeh** [comment]
目前下载间隔调整为 500 到 1000 毫秒之间的一个随机值，因为我感觉2秒有点太长了，对于有几百章的书要下载很久。

**Comment by Demodi** [comment]
不知道点开就开始自动检测，也是开了几本，喜提5天封号 😭

**Comment by champkeh** [comment]
> 不知道点开就开始自动检测，也是开了几本，喜提5天封号 😭

都有什么操作可以描述一下嘛

**Comment by champkeh** [comment]
如果有遇到这个问题的，可以在这里详细描述一下都可能涉及的任何操作，和提供vid

我自己也一直在用，包括自动阅读也一直都在跑，下载的话，几乎每天都会下载5本左右，因为最近一直在开发，所以需要频繁测试下载功能，但到目前为止还没有遇到这个问题，我现在也不清楚具体是什么操作会导致封号

**Comment by Demodi** [comment]
> > 不知道点开就开始自动检测，也是开了几本，喜提 5 天封号 😭
> 
> 都有什么操作可以描述一下嘛

也是一样，就是扫码登陆，然后同步打开了几本书，后面数了下也是10本书，每一本都自动下载了，然后就各个客户端被登陆，扫码几次才提示 被暂时封号，8号后才能使用

**Comment by champkeh** [comment]
> > > 不知道点开就开始自动检测，也是开了几本，喜提 5 天封号 😭
> 
> > 
> 
> > 都有什么操作可以描述一下嘛
> 
> 
> 
> 也是一样，就是扫码登陆，然后同步打开了几本书，后面数了下也是10本书，每一本都自动下载了，然后就各个客户端被登陆，扫码几次才提示 被暂时封号，8号后才能使用

同步打开？是同时开了多个标签页嘛？每一本都自动下载是指的什么意思呀？抱歉真的没看懂这个操作

**Comment by Demodi** [comment]
> > > > 不知道点开就开始自动检测，也是开了几本，喜提 5 天封号 😭
> > 
> > 
> > > 
> > 
> > 
> > > 都有什么操作可以描述一下嘛
> > 
> > 
> > 也是一样，就是扫码登陆，然后同步打开了几本书，后面数了下也是 10 本书，每一本都自动下载了，然后就各个客户端被登陆，扫码几次才提示 被暂时封号，8 号后才能使用
> 
> 同步打开？是同时开了多个标签页嘛？每一本都自动下载是指的什么意思呀？抱歉真的没看懂这个操作

就是同时打开了多个标签页，我也不记得是我手动点了下载还是它自动扫描，因为我记得我打开了标签页，它就开始load多少多少页，和打包图片blabla。。然后就被登出了。。也没做其他操作，没有自动阅读，没有自动领取

**Comment by champkeh** [comment]
那就是说，多个标签页同时下载呗，不知道其他被封的是不是都是这样的，但这样的确很高概率会被检测到，因为正常情况下用户不可能同时去打开多本书去读。
我用我的小号试一下吧，但最好还是不要同时下载多本

**Comment by bu-code** [comment]
封号的主因是同时多开标签页下载(令我困惑的是真有同时下那么多书的需求？逐本下载应该能满足需求了)，上次另一个项目也是因为作者发现有滥用而关停的。用户思考理解、感激作者的开发从而更好地完善、保护项目更为重要。
以上都是碎碎念，从接触有版权性质的电子书至今看到过很多今人惋惜的事例不免有感而发。

**Comment by champkeh** [comment]
的确是，正常用户也就是下载那些自己的确很喜欢的书，大概率不会去打开多个标签页同时下载，还有就是我不是每个用户都限制一个月100次下载限制嘛，但是有个别用户不到5天就已经下了100本书了。这种大概率是书贩子下载下来去卖的，唉，说实在的，当初听到那个项目关了之后，我还特意去问了下作者，因为我也担心版权啥的纠纷问题。

这个项目我尽量不关吧，但是如果真到了那一天，我也没办法

**Comment by Demodi** [comment]
也是我操作问题导致。本意是看看那些找不到epub版本的有没有书，结果短期内同时下载了 🤦

**Comment by Demodi** [comment]
> 那就是说，多个标签页同时下载呗，不知道其他被封的是不是都是这样的，但这样的确很高概率会被检测到，因为正常情况下用户不可能同时去打开多本书去读。 我用我的小号试一下吧，但最好还是不要同时下载多本

一次打开一个标签页，短时间内不要下载多本应该没事。以后会注意的。

**Comment by timowei** [comment]
weread-scraper被投诉下架肯定就是有人滥用玩大了呗。之前我也在那位开发者那里回复，就是担心这种问题。

这里前两周star人数暴增，我就知道不好，明明更早时间就有人发帖说不小心使用就会封号，还有人要搞花样，真当wx傻么。还有些贩子，纯粹就是涸泽而渔了，管你封不封，先疯狂地满足自己再说。

我建议不要搞epub模式，太容易被书贩子滥用了。
