### ISSUE TITLE
老大，支持京东读书了？

### ISSUE THREAD

**Issue by bookoyo** [champkeh/wereadx#13]
看见测试京东读书？

**Comment by champkeh** [comment]
知乎上有个网友提了一下，我就试试，目前接口已经调通了，不过还没做成工具，后面如果想做的话也很方便，跟微信读书差不多。
代码在examples下面，感兴趣的话可以看看

另外，这个称呼有点奇怪哎😁

**Comment by bookoyo** [comment]
老大，俺纯废物，等你做出了再试吧~
