### ISSUE TITLE
老大，能否做个豆瓣阅读的插件或网站~

### ISSUE THREAD

**Issue by bookoyo** [champkeh/wereadx#15]
比如下面这个例子，但这个插件导出来的只是纯文本，不适合阅读~

https://github.com/Violin9906/Douban-eBook-Exporter

**Comment by champkeh** [comment]
👌🏻，我先研究下

**Comment by champkeh** [comment]
https://read.douban.com/reader/column/63849711/chapter/436904937/

先挖个坑，后面有时间再看
