### ISSUE TITLE
迁移插件形式

### ISSUE THREAD

**Issue by champkeh** [champkeh/wereadx#16]
Deno Deploy 非常适合一些小型项目快速部署，提供的免费计划配置如下：

<img width="1120" alt="image" src="https://github.com/champkeh/wereadx/assets/7316006/01501bb1-6062-4af3-a7ae-7354103542ff">

随着服务端的操作越来越复杂，很容易超出 Deno Deploy 免费计划的限额，比如 CPU 时间：

<img width="1125" alt="image" src="https://github.com/champkeh/wereadx/assets/7316006/3819329f-b4fa-4429-aa0f-baf7868a800a">

<img width="1229" alt="image" src="https://github.com/champkeh/wereadx/assets/7316006/13f6adf6-9611-4a93-9f1b-e9273fba6ec8">

之前也曾为了避免内存超限额而将 html 整合工作移至客户端处理，详情查看 #4 
并且也极力避免在服务端生成 epub 格式，#2 
都是为了尽量减少服务端的资源消耗，但仍然不能完全避免。

因此，想要寻找一个更合适的服务器部署方案，要求有如下几点：
- 免费（毕竟我也没有从这个项目获取任何报酬，不可能部署在付费的服务器上的）
- 资源尽量可以满足现有需求

如果小伙伴们有推荐的方案，欢迎留言，谢谢！

**Comment by champkeh** [comment]
还有一种方式就是，完全在本地运行，参考 readme 中的 [**本地运行**](https://github.com/champkeh/wereadx#%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C) 说明，这种方式是在本地启动了一个服务器，并且没有任何资源限制。

如果真的没有合适的部署方案的话，可以用这种方式使用。

**Comment by bookoyo** [comment]
做个插件或者油猴脚本，也可以吧？

比如这个被作者停更关闭的开源脚本：https://github.com/leic4u/WeRead-Scraper

**Comment by champkeh** [comment]
对插件开发不太熟悉，不过我总感觉插件会有很多限制，比如跨域啥的。等有时间调研一下

**Comment by banhgao** [comment]
油猴脚本跨域应该没有跨域限制

**Comment by champkeh** [comment]
> 油猴脚本应该没有跨域限制

测试了下插件，的确是可以跨越下载的。

目前还是主要以服务器部署为主进行开发，等所有功能都差不多的时候，再考虑迁移到Chrome插件

**Comment by Rhilip** [comment]
如果是浏览器插件，定时任务的话 可以使用 [`chrome.alarms`](https://developer.chrome.com/docs/extensions/reference/alarms/) 方法实现

**Comment by champkeh** [comment]
> 如果是浏览器插件，定时任务的话 可以使用 [`chrome.alarms`](https://developer.chrome.com/docs/extensions/reference/alarms/) 方法实现

嗯，这个我知道，但是这个应该要打开浏览器才可以吧？

**Comment by bookoyo** [comment]
> > 油猴脚本应该没有跨域限制
> 
> 测试了下插件，的确是可以跨越下载的。
> 
> 目前还是主要以服务器部署为主进行开发，等所有功能都差不多的时候，再考虑迁移到Chrome插件
> 
> 迁移到插件的部分主要是下载功能，自动阅读、兑换体验卡等因为需要定时任务执行，所以不适合插件的形式，这部分仍然会保留服务器部署，但是这些不需要耗费太多资源，所以不再考虑迁移其他服务器部署方案了，还是用 Deno Deploy方式部署，毕竟我也比较熟悉这个方案。
> 
> 多谢 @banhgao @bookoyo 提供思路，这个 issue 就用于记录迁移插件的进度吧。

油猴脚本也可以，比插件应该更简单、适用~

**Comment by aloeJun** [comment]
Vercel可以考虑一下

**Comment by champkeh** [comment]
> Vercel可以考虑一下

嗯嗯，谢谢你的建议，不过目前已经弃坑了(某些不可避免的原因)
