### ISSUE TITLE
请帮忙看下：本地部署无法下载

### ISSUE THREAD

**Issue by bu-code** [champkeh/wereadx#17]
**详细描述一下遇到的问题**
安装deno、clone项目到本地部署后，运行“deno task dev”后，浏览器打开http://localhost:8000  虽可正常扫码登录，但下载时报错无法正常下载：
"文件名、目录名或卷标语法不正确。 (os error 123): readfile '/D:/xxx/xxx/wereadx/src/frontend/assets/styles/reset.css'"(路径中无中文、空格)

**期望的结果**
自己无法解决特向大佬求助。

**书籍BookID**
试了几本书籍都是一样的报错。

**Comment by champkeh** [comment]
> 文件名、目录名或卷标语法不正确。 (os error 123): readfile '/C:/Users/1990/Desktop/0000/88/wereadx-master/src/frontend/assets/styles/reset.css'

看起来像是 Windows 上读取文件报错了，我用的是 Mac，估计是没有考虑到 Windows 路径的问题，我找个环境试一下

**Comment by liuchaonuaa** [comment]
我也是，本地运行报了这个错

**Comment by champkeh** [comment]
😂，我同事电脑安装deno没成功，等我用 docker 试一下吧

**Comment by champkeh** [comment]
@liuchaonuaa @bu-code 已修复，重新拉下代码再试下

**Comment by liuchaonuaa** [comment]
https://github.com/champkeh/wereadx/issues/22


我用本地 下载的 用 calibre 也是出现类似上面错误，昨天用你的下载下来就没有。但是本地的用 IcecreamEbookReader 是可以打开的。 链接：https://pan.baidu.com/s/1kFz2LMtVU4KrNC2CtRERhw
提取码：swzu 


| |
刘超
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月1日 17:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [champkeh/wereadx] 请帮忙看下：本地部署无法下载 (Issue #17) |

@***@***.*** 已修复，重新拉下代码再试下

**Comment by bu-code** [comment]
> @liuchaonuaa @bu-code 已修复，重新拉下代码再试下

感谢神速，已经正常了。
