### ISSUE TITLE
跟着部署到Deno的，扫码登陆后总是自动掉线是什么原因呢？

### ISSUE THREAD

**Issue by sola237** [champkeh/wereadx#18]
**详细描述一下遇到的问题**

**期望的结果**

**书籍BookID**
如果涉及到特定书籍，请提供书籍的 bookId

**Comment by champkeh** [comment]
在 https://weread.deno.dev/ 这个上面能正常登录吗？

**Comment by champkeh** [comment]
看下后台的log里面都有什么有用的信息嘛

**Comment by champkeh** [comment]
我刚用我的小号部署了一遍，除了下载的时候报了一个错误(因为我没配置 DATABASE_URL 这个环境变量)，好像没遇到什么问题

**Comment by sola237** [comment]
可以正常登陆，也可以正常月度，只是隔一阵子再打开又要扫码重新登陆。看自动阅读进度那里也没有更新，后台log是去哪里看呢~

**Comment by sola237** [comment]
讲错了  自动阅读那里会更新 只是掉线后就不再更新。比如我昨天扫码登陆了，今天打开又要重新扫码登陆，进去看阅读时长更新的最终时间是昨天中午

**Comment by sola237** [comment]
![image](https://github.com/champkeh/wereadx/assets/63141812/20696097-d5d6-499b-bb2e-453684b62389)
我这个定时应该没问题，为什么后面提示下一次的时间不对

**Comment by champkeh** [comment]
> ![image](https://user-images.githubusercontent.com/63141812/279918343-20696097-d5d6-499b-bb2e-453684b62389.png) 我这个定时应该没问题，为什么后面提示下一次的时间不对

因为后面那个是 UTC 时间，要加8个小时才是北京时间

**Comment by champkeh** [comment]
> 讲错了 自动阅读那里会更新 只是掉线后就不再更新。比如我昨天扫码登陆了，今天打开又要重新扫码登陆，进去看阅读时长更新的最终时间是昨天中午

这个可以参考 #5 ，应该是某些账号的问题，目前好像没有解决方案

**Comment by sola237** [comment]
![image](https://github.com/champkeh/wereadx/assets/63141812/39e402f0-fa80-470d-8dca-507a8f0609d7)
我看cf后台的日志是这样

**Comment by sola237** [comment]
账号问题么= =  那估计是没办法了
对了。。我一个网站可以扫码2个账号吗，另一个开隐私模式的话

**Comment by champkeh** [comment]
你可以把 LocalStorage 里面的 token 删了，就可以登录另一个账号了
