### ISSUE TITLE
请教在 Deno Deploy 的设置页面，添加环境变量内容填写

### ISSUE THREAD

**Issue by fudadds** [champkeh/wereadx#19]
**详细描述一下遇到的问题**
1.  已按说明在 Deno Deploy 部署成功，但环境变量部分不知道写什么，目前为空
2. 在 CloudFlare 控制台添加一个 worker 自动阅读的触发器，但目前错误数量为100% 成功0 ，不知道是否和 环境变量没填有关系
**期望的结果**

**书籍BookID**
如果涉及到特定书籍，请提供书籍的 bookId

**Comment by champkeh** [comment]
`DATABASE_URL`这个环境变量唯一的作用就是记录下载历史数据，也就是这下面这块会用到：

https://github.com/champkeh/wereadx/blob/95981795bab5a981122d26f8f735f3b864ad0e77/src/kv/download.ts#L29-L36

跟自动阅读没有关系。

> 在 CloudFlare 控制台添加一个 worker 自动阅读的触发器，但目前错误数量为100% 成功0 

方便贴一下你的 worker 代码吗？或者在浏览器访问 `https://[你的部署域名]/cron/read/v2` 看看能不能访问。

**Comment by fudadds** [comment]
> `DATABASE_URL`这个环境变量唯一的作用就是记录下载历史数据，也就是这下面这块会用到：
> 
> https://github.com/champkeh/wereadx/blob/95981795bab5a981122d26f8f735f3b864ad0e77/src/kv/download.ts#L29-L36
> 
> 跟自动阅读没有关系。
> 
> > 在 CloudFlare 控制台添加一个 worker 自动阅读的触发器，但目前错误数量为100% 成功0
> 
> 方便贴一下你的 worker 代码吗？或者在浏览器访问 `https://[你的部署域名]/cron/read/v2` 看看能不能访问。
代码为 
export default {
    async scheduled(event, env, ctx) {
        // 注意：此处的域名替换成你自己部署的域名
        const resp = await fetch('https://late-lobster-97.deno.dev/cron/read/v2')
        console.log(await resp.text())
    },
};

尝试手动访问 https://late-lobster-97.deno.dev/cron/read/v2
回显为 {"code":0,"msg":"阅读任务执行完成"}  

刚才尝试把cron改为每分钟触发，查看CloudFlare 控制台 
查看结果
总计122
成功3.28%   4
错误数量 96.72%   118
![cron事件](https://github.com/champkeh/wereadx/assets/112491542/f64b4fe6-ed8e-4038-8e78-bf7407656833)


查看 Deno Deploy的log 目前正常  
![Uploading 当前每分钟一次正常.jpg…]()


之前存在一个失败，是否有影响
![部分失败记录](https://github.com/champkeh/wereadx/assets/112491542/d9d73944-438e-49f1-9ed1-8ad9244cda41)

**Comment by champkeh** [comment]
> 刚才尝试把cron改为每分钟触发，查看CloudFlare 控制台
查看结果
总计122
成功3.28% 4
错误数量 96.72% 118

这个错误率感觉也有点离谱，会不会是在部署成功之前就已经设置了这个触发器？

> 之前存在一个失败，是否有影响

这个警告是正常的，属于Cookie过期，程序会自动刷新的。
但是如果出现红色的错误，就表示程序没办法自动刷新Cookie了，需要重新扫码登录才行。参考 #5
