### ISSUE TITLE
支持导出其他电子书格式

### ISSUE THREAD

**Issue by champkeh** [champkeh/wereadx#2]
https://scribemedia.com/epub-vs-mobi/

**Comment by champkeh** [comment]
由于在服务端生成 epub/azw3 等非 html 格式需要消耗额外资源，所以不考虑服务端生成的方案。

目前找到一个似乎可行的客户端生成 epub 的方案，[Generating an EPUB File in the Browser](https://blog.jim-nielsen.com/2022/generating-epub-file-in-browser/)，因此在这里记录一下。

**Comment by lj1998008** [comment]
兄弟，这个啥意思啊：
"文件名、目录名或卷标语法不正确。 (os error 123): readfile '/C:/Users/1990/Desktop/0000/88/wereadx-master/src/frontend/assets/styles/reset.css'"

**Comment by champkeh** [comment]
> 文件名、目录名或卷标语法不正确。 (os error 123): readfile '/C:/Users/1990/Desktop/0000/88/wereadx-master/src/frontend/assets/styles/reset.css'

看起来像是 Windows 上读取文件报错了，我用的是 Mac，所有估计没有考虑到 Windows 路径的问题，我找个环境试一下

**Comment by lj1998008** [comment]
> > 文件名、目录名或卷标语法不正确。 (os error 123): readfile '/C:/Users/1990/Desktop/0000/88/wereadx-master/src/frontend/assets/styles/reset.css'
> 
> 看起来像是 Windows 上读取文件报错了，我用的是 Mac，所有估计没有考虑到 Windows 路径的问题，我找个环境试一下

谢谢

**Comment by lj1998008** [comment]
有的目录没有细分，比如：1c532a10813ab7456g017cfd

**Comment by champkeh** [comment]
> 1. 有的目录没有细分，比如：1c532a10813ab7456g017cfd
> 2. 注释能弄成点击（比如[1]）跳转到注释位置并可以点击返回么，比如：714323a071db55667144130

能详细描述一下嘛，具体是哪部分目录没有细分？还有注释能举个例子，比如哪一章第几个注释

**Comment by champkeh** [comment]
azw3目前没有计划进行支持，如果需要的话，可以自行用epub进行转换。

关于epub格式的问题，统一在 #30 下面讨论
