### ISSUE TITLE
epub文件中原书的多级目录结构丢失，全部变为一级；封面丢失

### ISSUE THREAD

**Issue by 27Strokes** [champkeh/wereadx#21]
非常好的项目！之前一直使用weread-spy，但长篇幅的书本的成功率非常低，一旦超时需要重头运行，几乎是彩票概率。这个项目很好的解决了这个问题，目前下载成功率100%，非常推荐！感谢作者！

**详细描述一下遇到的问题**
1. 下载的epub文件中原书的多级目录结构丢失，目录仍存在，但全部变为一级；
2. 封面不显示

**期望的结果**
1. 下载正确的目录结构；
2. 正确关联封面

**书籍BookID**
下载了多个书籍，均有这种现象出现，可能是普遍问题

**Comment by champkeh** [comment]
多谢提供反馈

1. 目录的层级问题的确没考虑到
2. 封面图是指的 html 版本里面第一页的那个图片吗？这个图片好像有时候会下载失败，不知道为什么，不过书籍详情接口也会返回封面图地址，但如果直接用这个做封面图的话，有可能会跟第一页的那张图片重复。我再想想怎么弄好点吧。

**Comment by champkeh** [comment]
看了下这个 weread-spy 项目，感觉 epubcheck lint 思路不错，感觉我也可以搞一下，用于验证生成的 epub 质量

**Comment by lj1998008** [comment]
> 看了下这个 weread-spy 项目，感觉 epubcheck lint 思路不错，感觉我也可以搞一下，用于验证生成的 epub 质量

spy这个很好用，就是最近失效了

**Comment by champkeh** [comment]
> > 看了下这个 weread-spy 项目，感觉 epubcheck lint 思路不错，感觉我也可以搞一下，用于验证生成的 epub 质量
> 
> 
> 
> spy这个很好用，就是最近失效了

很正常，这种项目只要微信改了代码，大部分都会失效，都需要不定期的跟进一下。
只不过他依赖于html结构，我依赖于接口字段而已。

**Comment by champkeh** [comment]
你这本书是自己上传的吧？自己上传的书好像都没有封面与元数据

**Comment by champkeh** [comment]
> 书籍内部的封面是成功下载的。

如果内部的封面能够下载下来的话，那可以考虑下用这个做成封面。

你这本书可以发我下吗？我自己上传下试试

**Comment by 27Strokes** [comment]
> 你这本书是自己上传的吧？自己上传的书好像都没有封面与元数据

1图这个就是通过wereadx从微信读书上下载的《毛泽东文集》再重新上传（由于版权限制，不能使用听书功能，故使用此办法）。若上传文件是有封面的，微信读书是可以显示封面的。举此例是为了说明下载的书籍无封面。《毛泽东文集》地址：https://weread.qq.com/web/reader/a8732200813ab71f5g016cd1? 您可以下载试一下，就是书籍本身有点大。

2图来自koodo reader导入通过wereadx从微信读书上下载的《毛泽东文集》的属性界面。可见无元数据。koodo reader中同样没有显示封面。

**Comment by champkeh** [comment]
![image](https://github.com/champkeh/wereadx/assets/7316006/c42c0f6e-3fbf-46d9-a6ad-d3b857c5b13c)

![image](https://github.com/champkeh/wereadx/assets/7316006/6947ab77-eb23-4c03-99fd-5dd9b93ff48d)

图1是微信读书原始的书，图2是通过 wereadx 下载之后再上传之后的书

对比可以发现，封面图、标题、作者、出版社这些元数据没有丢失，简介、出版时间、ISBN等丢失了。可能是微信没有识别出这些元数据，这个需要我再仔细研究下 EPUB 规范，看看是不是还有别的标签来表示这些元数据。

**Comment by 27Strokes** [comment]
> <img alt="image" width="882" src="https://user-images.githubusercontent.com/7316006/280045040-9ed9bc19-435f-434d-9acf-89edab3d7b53.png">
> 这本书太大了吧，导入了好几次都没导入成功😭
哈哈哈哈哈哈，看到你更新了！效率太高了！我试试！

**Comment by 27Strokes** [comment]
**目录层级、元数据、封面问题均完美解决！**

还有个可能的小改进，关于优化epub的（可能已经和本项目关系不大了）。

使用calibre编辑epub文件，发现每一篇篇头都有大量的格式设置，每一篇篇头的这一段都基本相同，篇幅甚至比正文本身还长，如下图：
![image](https://github.com/champkeh/wereadx/assets/99136619/a20d5cb2-4289-45bc-9237-a0e67e37a2fd)

感觉应该是可以精简和合并的。使用calibre删除无用的css规则，
![1698976422073](https://github.com/champkeh/wereadx/assets/99136619/9aaf4b6d-35ad-4bc2-a06a-2aebab8ba97d)

可以大幅度的降低文件大小，下图是对比
![image](https://github.com/champkeh/wereadx/assets/99136619/b20cb1ef-f634-4e9e-b1c3-a2a080fad99e)

作者可以考虑下这个改进（或许我再开一个issue），非常感谢！

**Comment by champkeh** [comment]
> > <img alt="image" width="882" src="https://user-images.githubusercontent.com/7316006/280045040-9ed9bc19-435f-434d-9acf-89edab3d7b53.png">
> 
> > 这本书太大了吧，导入了好几次都没导入成功😭
> 
> 哈哈哈哈哈哈，看到你更新了！效率太高了！我试试！
> 
> 

我就更新了下目录，封面啥也没干🤣

**Comment by champkeh** [comment]
> **目录层级、元数据、封面问题均完美解决！**
> 
> 
> 
> 还有个可能的小改进，关于优化epub的（可能已经和本项目关系不大了）。
> 
> 
> 
> 使用calibre编辑epub文件，发现每一篇篇头都有大量的格式设置，每一篇篇头的这一段都基本相同，篇幅甚至比正文本身还长，如下图：
> 
> ![image](https://github.com/champkeh/wereadx/assets/99136619/a20d5cb2-4289-45bc-9237-a0e67e37a2fd)
> 
> 
> 
> 感觉应该是可以精简和合并的。使用calibre删除无用的css规则，
> 
> ![1698976422073](https://github.com/champkeh/wereadx/assets/99136619/9aaf4b6d-35ad-4bc2-a06a-2aebab8ba97d)
> 
> 
> 
> 可以大幅度的降低文件大小，下图是对比
> 
> ![image](https://github.com/champkeh/wereadx/assets/99136619/b20cb1ef-f634-4e9e-b1c3-a2a080fad99e)
> 
> 
> 
> 作者可以考虑下这个改进（或许我再开一个issue），非常感谢！
> 
> 

这个我起初也考虑过，把样式抽成一个公共的文件，但发现有的书的样式并不一样，如果要精简的话就要分析css文件，把公共的样式抽取出来，不一样的保留。这个工作量目前来说还是有点大，不是现阶段的目标

**Comment by champkeh** [comment]
或者如果我发现有第三方库有这个功能的话，我再集成一下

**Comment by champkeh** [comment]
可以单独开一个epub优化的，因为现在的格式也是有问题的，lint检查没通过，比如css里面的网络资源(背景图片)没有下载下来，id重复等，但是好像并不影响阅读。

**Comment by 27Strokes** [comment]
> 可以单独开一个epub优化的，因为现在的格式也是有问题的，lint检查没通过，比如css里面的网络资源(背景图片)没有下载下来，id重复等，但是好像并不影响阅读。

发现 https://github.com/magicdawn/weread-spy 这个项目生成的epub文件相对都很小（10Mb以内），作者不介意的话可以参考以下，防止重复造轮子

**Comment by champkeh** [comment]
> > 可以单独开一个epub优化的，因为现在的格式也是有问题的，lint检查没通过，比如css里面的网络资源(背景图片)没有下载下来，id重复等，但是好像并不影响阅读。
> 
> 
> 
> 发现 https://github.com/magicdawn/weread-spy 这个项目生成的epub文件相对都很小（10Mb以内），作者不介意的话可以参考以下，防止重复造轮子

嗯嗯，我看看
