### ISSUE TITLE
下载epub格式的电子书打开时显示错误。

### ISSUE THREAD

**Issue by JinZhong-RouSong** [champkeh/wereadx#22]
**详细描述一下遇到的问题**

**期望的结果**

**书籍BookID**
如果涉及到特定书籍，请提供书籍的 bookId

**Comment by JinZhong-RouSong** [comment]
calibre, version 6.10.0
错误： 无法加载书籍: 无法打开位于 D:\Program Files\Calibre Portable\Calibre Library\Yi Yi Wen\Xie Shi Yu Shu Qing _Cong Yue Yu Pi (172)\Xie Shi Yu Shu Qing _Cong Yue Y - Yi Yi Wen.epub 的书籍，点击“查看详情”获取更多信息。

Failed to convert book: D:\Program Files\Calibre Portable\Calibre Library\Yi Yi Wen\Xie Shi Yu Shu Qing _Cong Yue Yu Pi (172)\Xie Shi Yu Shu Qing _Cong Yue Y - Yi Yi Wen.epub with error:
InputFormatPlugin: EPUB Input running
on D:\Program Files\Calibre Portable\Calibre Library\Yi Yi Wen\Xie Shi Yu Shu Qing _Cong Yue Yu Pi (172)\Xie Shi Yu Shu Qing _Cong Yue Y - Yi Yi Wen.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 821, in viewer_main
  File "calibre\srv\render_book.py", line 812, in render_for_viewer
  File "calibre\srv\render_book.py", line 790, in render
  File "calibre\srv\render_book.py", line 603, in process_exploded_book
  File "calibre\srv\render_book.py", line 263, in create_cover_page
  File "calibre\srv\render_book.py", line 216, in find_epub_cover
  File "calibre\ebooks\oeb\polish\cover.py", line 284, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 430, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 41, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes

**Comment by champkeh** [comment]
可以提供一份这个有问题的epub文件嘛

**Comment by JinZhong-RouSong** [comment]
> 可以提供一份这个有问题的epub文件嘛

我现在下每一本书都这样<哭>，昨天晚上下的书没有封面，但是内容完好；今天下的所有书都有封面有简介，但就是打不开，用安卓APP打开显示乱码。都是免费书

**Comment by champkeh** [comment]
因为我最近更新的很频繁，你昨天晚上下的时候的代码，跟现在下的代码都不一样，有问题很正常

**Comment by liuchaonuaa** [comment]
我用本地 下载的 用 calibre 也是出现类似这个错误，昨天用你的下载下来就没有。但是本地的用 IcecreamEbookReader 是可以打开的。   链接：https://pan.baidu.com/s/1kFz2LMtVU4KrNC2CtRERhw 
提取码：swzu

**Comment by JinZhong-RouSong** [comment]
> 因为我最近更新的很频繁，你昨天晚上下的时候的代码，跟现在下的代码都不一样，有问题很正常

那请问我该怎么操作呢

**Comment by champkeh** [comment]
> 我用本地 下载的 用 calibre 也是出现类似这个错误，昨天用你的下载下来就没有。但是本地的用 IcecreamEbookReader 是可以打开的。 链接：https://pan.baidu.com/s/1kFz2LMtVU4KrNC2CtRERhw 提取码：swzu

哇，好大呀🤣

**Comment by champkeh** [comment]
> 那请问我该怎么操作呢

有可能是我修改 epub 元数据的时候搞错了，不过我刚又下载了一本书，用苹果的 Books 是可以打开的，用 Sigil 打开也没报任何警告，所以有可能是你下载的书的格式有问题，你可以提供一本有问题的epub文件我看下嘛

**Comment by JinZhong-RouSong** [comment]
> > 那请问我该怎么操作呢
> 
> 有可能是我修改 epub 元数据的时候搞错了，不过我刚又下载了一本书，用苹果的 Books 是可以打开的，用 Sigil 打开也没报任何警告，所以有可能是你下载的书的格式有问题，你可以提供一本有问题的epub文件我看下嘛

好的好的这是其中一本https://wwi.lanzoup.com/iWbUQ1dfty3g

**Comment by champkeh** [comment]
> 好的好的这是其中一本https://wwi.lanzoup.com/iWbUQ1dfty3g

![image](https://github.com/champkeh/wereadx/assets/7316006/6e712948-fd53-4e9b-ab78-b2497e56503e)
![image](https://github.com/champkeh/wereadx/assets/7316006/feccff83-96f3-42e6-8b9d-f0e6aa03f518)

我用 Books 和 Sigil 都可以打开呀😂，应该是阅读器的问题，你用的什么阅读器？

**Comment by JinZhong-RouSong** [comment]
> > 好的好的这是其中一本https://wwi.lanzoup.com/iWbUQ1dfty3g
> 
> ![image](https://github.com/champkeh/wereadx/assets/7316006/6e712948-fd53-4e9b-ab78-b2497e56503e)
> ![image](https://github.com/champkeh/wereadx/assets/7316006/feccff83-96f3-42e6-8b9d-f0e6aa03f518)
> 
> 我用 Books 和 Sigil 都可以打开呀😂，应该是阅读器的问题，我试下 calibre 看看
> 
> 
> 
> 

好的麻烦看看，因为安卓设备上打开就是乱码😭，电子阅读器也一样😭😭

**Comment by champkeh** [comment]
> 我用本地 下载的 用 calibre 也是出现类似这个错误，昨天用你的下载下来就没有。但是本地的用 IcecreamEbookReader 是可以打开的。 链接：https://pan.baidu.com/s/1kFz2LMtVU4KrNC2CtRERhw 提取码：swzu

应该也是阅读器的问题

**Comment by JinZhong-RouSong** [comment]
> > 我用本地 下载的 用 calibre 也是出现类似这个错误，昨天用你的下载下来就没有。但是本地的用 IcecreamEbookReader 是可以打开的。 链接：https://pan.baidu.com/s/1kFz2LMtVU4KrNC2CtRERhw 提取码：swzu
> 
> 应该也是阅读器的问题

应该是格式的问题…毕竟无论掌阅还是微信读书还是电子阅读器，都是最适配各种电子书格式的😂，用它们都打不开

**Comment by champkeh** [comment]
是的，不过我这边下载 calibre 好慢，我还是先添加 epubcheck lint 检查吧，只要这个通过了，应该大部分阅读器都没问题

**Comment by JinZhong-RouSong** [comment]
> 是的，不过我这边下载 calibre 好慢，我还是先添加 epubcheck lint 检查吧，只要这个通过了，应该大部分阅读器都没问题

好的好的，我电脑里的calibre超过100M没办法上传蓝奏云，你要是能用阿里云盘的话我发给你

**Comment by champkeh** [comment]
你电脑里面安装的是 Windows 版吧？我要 MacOS 的，我回家用家里面的网络试试吧

**Comment by champkeh** [comment]
<img width="1504" alt="image" src="https://github.com/champkeh/wereadx/assets/7316006/4ceccd90-845e-4408-8d92-fcef55e90472">

用 epubcheck 检查了下，的确有2个错误

**Comment by champkeh** [comment]
已修复 @liuchaonuaa @JinZhong-RouSong

**Comment by liuchaonuaa** [comment]
嗯嗯   可以了，谢谢

**Comment by JinZhong-RouSong** [comment]
> 已修复 @liuchaonuaa @JinZhong-RouSong 

OK了OK了👍🏻👍🏻👍🏻
