### ISSUE TITLE
明白了,谢谢

### ISSUE THREAD

**Issue by lj1998008** [champkeh/wereadx#23]
明白了,谢谢

**Comment by champkeh** [comment]
![image](https://github.com/champkeh/wereadx/assets/7316006/a7aca224-4258-4266-9be4-3d73d3492393)

不支持下载付费内容，需要使用付费会员卡才可下载这部分内容

**Comment by lj1998008** [comment]
> ![image](https://user-images.githubusercontent.com/7316006/279662363-a7aca224-4258-4266-9be4-3d73d3492393.png)
> 
> 不支持下载付费内容，需要使用付费会员卡才可下载这部分内容

ok
多谢
