### ISSUE TITLE
防止被盗刷的解决方案

### ISSUE THREAD

**Issue by Loongphy** [champkeh/wereadx#27]
为了避免恶意盗刷接口，有必要增加鉴权

**Comment by champkeh** [comment]
感谢提供的建议

这个问题我也有考虑过，起初只是不想让别人把我的免费额度给刷完了，所以加了个每月下载额度的限制，不过目前没有时间做这块功能(目前在优化 epub 的格式，等 epub 优化的差不多的时候，再考虑做这一块。或者如果你有兴趣的话，可以参与进来一块开发)

现在采用的机制比较基础，要求每个接口都要带`token`参数，有了这个参数，就可以知道用户的`vid`
后续如果要做的话，可以基于`vid`进行限制，主要是对调用频率的限制(加签名啥的意义不大，因为微信读书就是用的签名加各种加密)

最终可以做个配置，是否开启限制，因为对于私有部署就没必要进行限制了。

**Comment by Loongphy** [comment]
对我个人来说，是担心 cron API 被恶意滥用，目前这块没有做请求限制。关于安全这块没有太多经验，简单点可以增加个自定义配置，请求时必须匹配该参数才能请求。
（PR 可以，但是我太懒了，需要等等🤣 关于请求限制如果有更好的建议，可以提出来

**Comment by champkeh** [comment]
但是有一个问题就是，deno doploy的请求量也是有限额的，这个感觉没办法避免被盗刷，只能尽量不要暴露cron的接口域名

**Comment by champkeh** [comment]
总结一下，关于盗刷大概分三类:

- 流量盗刷
- 前端接口盗刷
- cron任务盗刷

流量盗刷目前没有任何解决方案，只能寄希望于deno deploy提供解决方案了。
前端接口盗刷，可以根据上面提出的限制vid用户的请求频率。
cron任务本质上属于后端服务间调用，这种场景通常做法是公私钥加密加签，但是为了简单起见，可以只配置一个固定的随机字符串参数（类似于密码的功能）

**Comment by champkeh** [comment]
补充一点，deno deploy应该很快就会支持cron功能，到时候测试一下效果看看怎么样，如果可以的话，cron任务都可以改为deno自己的实现，就不需要用cloudflare去触发了，也就不存在第三点的问题了
