### ISSUE TITLE
支持飞书、钉钉通知

### ISSUE THREAD

**Issue by Loongphy** [champkeh/wereadx#29]
能够利用 cron 定时通知消息，以确认阅读时长、脚本是否正常运作

**Comment by Loongphy** [comment]
Maybe I can finish it this week.

**Comment by champkeh** [comment]
> Maybe I can finish it this week.

👍

**Comment by champkeh** [comment]
钉钉通知是要创建一个组织，然后用机器人发通知吗？没做过这块

**Comment by fudadds** [comment]
我在使用青龙面板的时候，可以sendNotify.js 调用各种api发送通知，  可以参考https://github.com/ccwav/QLScript2/blob/main/sendNotify.js

**Comment by champkeh** [comment]
> 我在使用青龙面板的时候，可以sendNotify.js 调用各种api发送通知，  可以参考https://github.com/ccwav/QLScript2/blob/main/sendNotify.js

这个项目是什么呀，没怎么看懂🥲

**Comment by fudadds** [comment]
> > 我在使用青龙面板的时候，可以sendNotify.js 调用各种api发送通知，  可以参考https://github.com/ccwav/QLScript2/blob/main/sendNotify.js
> 
> 这个项目是什么呀，没怎么看懂🥲

青龙, 一个支持python3、javascript、shell、typescript 的定时任务管理面板;
我是建个容器取拉各种签到的库，例如 
https://github.com/mrabit/aliyundriveDailyCheck 进行阿里云盘签到 ；

每个任务执行后通过调用sendNotify.js发送通知，

支持的通知方式挺全的，自建的gotify，
server酱，go-cqhttp，pushdeer，Bark App，tg bot，钉钉bot，企业微信bot，企业微信应用消息，飞书，iGot，push plus，WxPusher

**Comment by champkeh** [comment]
> > > 我在使用青龙面板的时候，可以sendNotify.js 调用各种api发送通知，  可以参考https://github.com/ccwav/QLScript2/blob/main/sendNotify.js
> > 
> > 
> > 这个项目是什么呀，没怎么看懂🥲
> 
> 青龙, 一个支持python3、javascript、shell、typescript 的定时任务管理面板; 我是建个容器取拉各种签到的库，例如 https://github.com/mrabit/aliyundriveDailyCheck 进行阿里云盘签到 ；
> 
> 每个任务执行后通过调用sendNotify.js发送通知，
> 
> 支持的通知方式挺全的，自建的gotify， server酱，go-cqhttp，pushdeer，Bark App，tg bot，钉钉bot，企业微信bot，企业微信应用消息，飞书，iGot，push plus，WxPusher

感谢详细的解答，但对这一块完全没什么概念，看的一知半解的

**Comment by champkeh** [comment]
已经加了邮件通知，稍后更新下 readme 说明
