### ISSUE TITLE
关于epub的问题，统一在这里讨论

### ISSUE THREAD

**Issue by champkeh** [champkeh/wereadx#30]
不管是注释，还是目录，还是epubcheck失败，都统一在这里记录与讨论

**Comment by rainjwy** [comment]
使用自己部署的域名，更新到最新版发现，epub格式比测试版好用了很多，解决了之前测试版的很多问题。不用修复错误，目录层级正确，内文下载完全……看得出作者大大很用心！但还是存在一些小问题，我目前发现的有封面图片丢失、内文部分图片丢失，希望下一版本可以改进~
