### ISSUE TITLE
希望能够添加一个退出账号的功能

### ISSUE THREAD

**Issue by changanshichangan** [champkeh/wereadx#31]
因为我之前是在公用的网址登录了，现在重新搭建了一个，我希望能够退出公用网址，不用浪费公用的次数。

**Comment by champkeh** [comment]
你说的公用的次数是指的自动阅读吗？自动阅读有停止功能的，在这里：

![image](https://github.com/champkeh/wereadx/assets/7316006/b71699a2-a3bb-40f9-8e6e-4edd361a7dc1)

最近在做通知功能，需要新增加一个配置页面，到时候退出按钮放在这个页面里面，退出放在顶部导航栏感觉有点怪

**Comment by changanshichangan** [comment]
哦哦哦，我没注意看，没看到停止按钮
