### ISSUE TITLE
HTML格式，图片没有嵌入到文档中，而是以链接的形式

### ISSUE THREAD

**Issue by rainjwy** [champkeh/wereadx#33]
问题：下载html后用word打开，发现在断网状态下，图片部分无法显示，提示“无法显示链接的图片。该文件可能已被移动、重命名或删除。请验证该链接是否指向正确的文件和位置。”
解决办法：参照https://zhuanlan.zhihu.com/p/583739793里的教程，在word中依次点击“文件”→“信息”→“编辑指向图片的链接”，在“源文件”数据框中选择所有需要保存在文档中的图片对象，勾选下面的“将图片保存在文档中”即可。
不得不承认，这样手工操作有些麻烦，希望作者大大可以解决这个bug！
BTW：下载epub（测试）后，可以解决图片嵌入问题，但是同样有些麻烦——用calibre ebook viewer不能正常打开，用calibre ebook editor修复错误后，可以正常打开，但是发现封面页有乱码且封面图片丢失，另外还有目录失去层级的问题。
之前没怎么试过下载epub（因为弹出错误），觉得html格式就挺好，下载后用word打开保存为docx，目录层级很清晰 ，用calibre转换成epub/azw3/mobi也很容易，可惜有无法嵌入图片的bug，需要手工操作才行……

**Comment by bu-code** [comment]
这个不算bug，可以向作者提议加个“嵌入图片到html”的选项，不过我个人绝对没什么必要，要有图片的需求直接下epub就行。
现在版本我下的epub都正常了，相信不断完善之后epub就没有你所说的问题了。

**Comment by rainjwy** [comment]
> 这个不算bug，可以向作者提议加个“嵌入图片到html”的选项（之前有个项目是用base64的形式），不过我个人绝对没什么必要，要有图片的需求直接下epub就行。 现在版本我下的epub都正常了，相信不断完善之后epub就没有你所说的问题了。
我其实觉得epub格式问题很大，需要手动修复＋目录层级丢失不说，目录其实有一部分丢失，图片也有一部分丢失，使用部署到deno.dev的个人域也不能把书籍下载完全，不愧为“测试版”……你下载的epub完全正常？

**Comment by bu-code** [comment]
> > 这个不算bug，可以向作者提议加个“嵌入图片到html”的选项（之前有个项目是用base64的形式），不过我个人绝对没什么必要，要有图片的需求直接下epub就行。 现在版本我下的epub都正常了，相信不断完善之后epub就没有你所说的问题了。
> 
> 我其实觉得epub格式问题很大，需要手动修复＋目录层级丢失不说，目录其实有一部分丢失，图片也有一部分丢失，使用部署到deno.dev的个人域也不能把书籍下载完全，不愧为“测试版”……你下载的epub完全正常？

你没更新吧？“测试”是之前的版本了。

**Comment by rainjwy** [comment]
> > > 这个不算bug，可以向作者提议加个“嵌入图片到html”的选项（之前有个项目是用base64的形式），不过我个人绝对没什么必要，要有图片的需求直接下epub就行。 现在版本我下的epub都正常了，相信不断完善之后epub就没有你所说的问题了。
> > 
> > 
> > 我其实觉得epub格式问题很大，需要手动修复＋目录层级丢失不说，目录其实有一部分丢失，图片也有一部分丢失，使用部署到deno.dev的个人域也不能把书籍下载完全，不愧为“测试版”……你下载的epub完全正常？
> 
> 你没更新吧？“测试”是之前的版本了。

小白想请教下，fork后怎么保持更新？

**Comment by bu-code** [comment]
> > > > 这个不算bug，可以向作者提议加个“嵌入图片到html”的选项（之前有个项目是用base64的形式），不过我个人绝对没什么必要，要有图片的需求直接下epub就行。 现在版本我下的epub都正常了，相信不断完善之后epub就没有你所说的问题了。
> > > 
> > > 
> > > 我其实觉得epub格式问题很大，需要手动修复＋目录层级丢失不说，目录其实有一部分丢失，图片也有一部分丢失，使用部署到deno.dev的个人域也不能把书籍下载完全，不愧为“测试版”……你下载的epub完全正常？
> > 
> > 
> > 你没更新吧？“测试”是之前的版本了。
> 
> 小白想请教下，fork后怎么保持更新？

已经偏离此issue，下书的需求与是否fork本项目无关。

**Comment by rainjwy** [comment]
> > > > > 这个不算bug，可以向作者提议加个“嵌入图片到html”的选项（之前有个项目是用base64的形式），不过我个人绝对没什么必要，要有图片的需求直接下epub就行。 现在版本我下的epub都正常了，相信不断完善之后epub就没有你所说的问题了。
> > > > 
> > > > 
> > > > 我其实觉得epub格式问题很大，需要手动修复＋目录层级丢失不说，目录其实有一部分丢失，图片也有一部分丢失，使用部署到deno.dev的个人域也不能把书籍下载完全，不愧为“测试版”……你下载的epub完全正常？
> > > 
> > > 
> > > 你没更新吧？“测试”是之前的版本了。
> > 
> > 
> > 小白想请教下，fork后怎么保持更新？
> 
> 已经偏离此issue，下书的需求与是否fork本项目无关。

嗯，公共域名经常出现下载不完全的问题，那我手动更新试试看吧

**Comment by champkeh** [comment]
> fork后怎么保持更新？

![image](https://github.com/champkeh/wereadx/assets/7316006/6b9be58f-c68f-4586-9bc6-fc0a5664aeb6)

因为会经常更新功能与修复bug，所以如果是使用的自己部署的版本，要先看下这里有没有更新，如果有就点击这个按钮更新到最新版本。

另外，公共服务因为用的人多，不推荐下载比较大的书籍(比如超过200章)，很容易出现下载中断的情况。

**Comment by champkeh** [comment]
html 版本不打算去加内嵌图片的功能，因为投入产出比不高

你可以在下载完 html 之后先用浏览器打开，等所有图片都加载完之后，用浏览器的**另存为**功能，把html里面的所有资源都保存一下就可以离线阅读了。

格式选后面两种，如下图：
![image](https://github.com/champkeh/wereadx/assets/7316006/c00479bb-5354-4212-9dc9-329c1cbab6cb)
![image](https://github.com/champkeh/wereadx/assets/7316006/ec350f83-fa2b-4615-8ae4-fc53ce402a61)

**Comment by rainjwy** [comment]
谢谢作者大大回复！更新到最新版发现，epub格式已经好了很多，但还是不够尽善尽美。虽然目录层级正确，正文下载完全，可惜依然存在封面图片丢失、内文部分图片丢失的问题，感觉还是html格式更加稳定……
