### ISSUE TITLE
还有希望让超多章节的书能完整下载吗？

### ISSUE THREAD

**Issue by timowei** [champkeh/wereadx#34]
下载的过程中发现时不时会出现书籍的内容不完全，后面内容丢失。尤其是书内容很多、章节超多的情况下。

以前用weread-scraper脚本虽然非常完善，但也有这样的问题的，一般是超过100章以上，之后的部分就下载不完全了。但是可以手动解决，可以在下载了100章左右，手动停止下载并先保存html；然后在中断的地方再手动开始下载，再视情况手动保存html。最后自己手动合并几个不同部分的html就好。

但wereadx就没法这么操作，遇上一些超多章节的书下载不全，也不好反复频繁地试，怕有封号风险。

是否可以考虑让人手动将书籍分成几个部分下载呢？或者还有其他什么解决方法么？感谢作者。

比如，bookId=33890244，真是死活下不下来了。

**Comment by champkeh** [comment]
使用最新版，优化了图片下载，对于图片较多，章节较多的，可以本地运行
