### ISSUE TITLE
在Deno Deploy重新部署时出错，需要协助

### ISSUE THREAD

**Issue by fudadds** [champkeh/wereadx#35]
**请详细描述一下遇到的问题**
按步骤在  Deno Deploy重新部署后，
访问网页时出现错误
![错误log2](https://github.com/champkeh/wereadx/assets/112491542/c2303044-918e-4507-b67b-fa481b5aca2c)
 502 Bad Gateway
The deployment failed while serving the request.

code: UNCAUGHT_EXCEPTION
查看log有报错
![错误log](https://github.com/champkeh/wereadx/assets/112491542/75fb0868-e022-44fd-b83f-68caa665bc69)

**期望的结果**

 
**运行平台**
Deno Deploy

**Comment by champkeh** [comment]
我加了几个环境变量，你可以看下最新的readme

**Comment by fudadds** [comment]
> 我加了几个环境变量，你可以看下最新的readme

感谢，按新的文档，添加环境变量后，问题已解决
![环境变量](https://github.com/champkeh/wereadx/assets/112491542/3553c912-c31c-4c80-9254-0509a0af076b)

**Comment by fudadds** [comment]
注意添加新的  环境变量

**Comment by champkeh** [comment]
还有部署问题嘛

**Comment by fudadds** [comment]
问题已解决
