### ISSUE TITLE
下载比较大的书籍时会出现内存超限额

### ISSUE THREAD

**Issue by champkeh** [champkeh/wereadx#4]
<img width="1324" alt="image" src="https://github.com/champkeh/wereadx/assets/7316006/cc6a148f-a9a4-4ccb-b88e-2130599fb490">

如上图所示，查看日志时发现有这样的错误，猜测可能跟现在的实现方式有关。

现在的实现方式为了简单，会把所有的内容先下载到服务器内存，等整本书下载完之后再统一发给客户端。这样就很容易出现上面的错误，所以需要优化成每下载一个章节都发给客户端，服务器不再保存

**Comment by champkeh** [comment]
目前已经改为单章传输，不再传输整本书了，整合工作会在客户端完成。
后续观察下会不会出现这个问题

**Comment by colin4k** [comment]
发现是每个字都会设置样式，导致导出的文件比较大，这个能否优化？

**Comment by champkeh** [comment]
> 发现是每个字都会设置样式，导致导出的文件比较大，这个能否优化？

这个的确是可以优化一下，现在是为了简单，就直接返回了微信读书最原始的样式。不过这个优化的优先级可能比较低，会先支持epub格式

**Comment by colin4k** [comment]
> > 发现是每个字都会设置样式，导致导出的文件比较大，这个能否优化？
> 
> 这个的确是可以优化一下，现在是为了简单，就直接返回了微信读书最原始的样式。不过这个优化的优先级可能比较低，会先支持epub格式

其实 epub 或者pdf都很容易搞定，因为有现成的成熟方案，比如导入 word 之后再导出 pdf，或者用sigil这个免费工具。我目前都是使用sigil导入wereadx导出的html进行处理生成epub，而且可以很方便的生成目录，但是由于目前导出的html中每个字都有样式，导致用sigil处理的时候很慢。

**Comment by champkeh** [comment]
ok，我先研究下这个方案，之前没找到合适的epub生成库，所以打算自己研究epub格式的

**Comment by champkeh** [comment]
大概看了下这个sigil工具，有以下几点是目前不太满意的：
- 好像没有api可以调用，所以需要自己安装一个软件去手动编辑，包括元数据与目录等，太麻烦了。

其实这些元数据及章节信息都已经有了，只是目前缺少一个生成epub文件的库。

所以这个方案目前暂不考虑，目前还是想直接用js生成epub文件，sigil可以作为一个补充工具方便进行二次编辑，但不适合直接将现有的html文件转为epub

**Comment by champkeh** [comment]
@colin4k 下载的 html 文件已经经过优化了，尺寸也比之前小了很多，你可以试试

**Comment by colin4k** [comment]
> @colin4k 下载的 html 文件已经经过优化了，尺寸也比之前小了很多，你可以试试

测试了3本书，注释效果很好，导出文件也不再像以前那样每个字都有样式导致尺寸较大了。
不过还有个小问题，就是epub文件没有默认添加封面，这个如果能处理下就更好了，感谢！

**Comment by champkeh** [comment]
嗯嗯，我也注意到这个了，还有一些元数据比如标题、作者、出版社等都还没有添加，这些都是可以加上去的
