### ISSUE TITLE
如何下载epub格式？

### ISSUE THREAD

**Issue by bookoyo** [champkeh/wereadx#7]
试了一下，下载的都是html

**Comment by champkeh** [comment]
对，epub目前还不支持

**Comment by champkeh** [comment]
> 大佬，大概要多久才会支持？

这个不能保证，但目前主要的工作就是处理 epub 格式，可以关注这个[issue](#2 )

**Comment by champkeh** [comment]
鉴于使用人数逐渐增多，暴露出的问题也越来越多，我打算优先处理 html 格式的各种问题，等 html 格式优化的差不多的时候，再考虑生成 epub 及其他格式。

**Comment by champkeh** [comment]
已初步支持下载 epub 格式，欢迎测试与提交反馈

**Comment by bookoyo** [comment]
> 已初步支持下载 epub 格式，欢迎测试与提交反馈

老大，epub貌似好像还是不能正常显示注释~

**Comment by champkeh** [comment]
> > 已初步支持下载 epub 格式，欢迎测试与提交反馈
> 
> 
> 
> 老大，epub貌似好像还是不能正常显示注释~

注释需要单独处理，还没搞

**Comment by champkeh** [comment]
已支持注释

**Comment by BeethovenWong** [comment]
大一点的书籍下载不完全，要完全下载需要自己部署一个本地运行吗？

**Comment by champkeh** [comment]
> 大一点的书籍下载不完全，要完全下载需要自己部署一个本地运行吗？

对，如果一本书超过300章的话，服务器很容易出现CPU超限额错误，会导致下载失败。本地运行的话不会出现这个问题

**Comment by BeethovenWong** [comment]
原来如此，感谢大佬！

**Comment by champkeh** [comment]
后面打算迁移到Chrome插件的形式，应该也不会出现这个问题。但是应该会很久之后了

**Comment by DesT-iny** [comment]
微信读书的注释是那种鼠标悬停在“注”的图标那里才会显示注释内容，在电脑上可以看到注释，在手机上好像还是看不到注释。注释的格式是这样的：<span class="reader_footer_note js_readerFooterNote" data-wr-co="2967" data-wr-footernote="【注释内容】"></span>，大佬能处理成能在kindle上看的那种弹注吗

**Comment by champkeh** [comment]
可以，这样估计得需要用 js 来做，等我研究下 epub 里面的 js

**Comment by Sipoon** [comment]
貌似有些书只下载到一半就停了，不完整，比如《施今墨医学全集》

**Comment by champkeh** [comment]
> 貌似有些书只下载到一半就停了，不完整，比如《施今墨医学全集》

浏览器控制台有报错信息嘛，如果有报错，就说明服务器出现cpu超限额错误了，这种就只能本地运行了

**Comment by Sipoon** [comment]
> 浏览器控制台有报错信息嘛，如果有报错，就说明服务器出现cpu超限额错误了，这种就只能本地运行了
谢谢提醒，本地运行就可以了，不知有以下提示有没影响的？
Close tag no opened match:[{"tag":"body","srcHtml":"<body>","isClosing":false,"pos":0,"srcPos":0}]"h1"
Close tag no opened match:[{"tag":"body","srcHtml":"<body>","isClosing":false,"pos":0,"srcPos":0}]"p"

**Comment by champkeh** [comment]
> > 浏览器控制台有报错信息嘛，如果有报错，就说明服务器出现cpu超限额错误了，这种就只能本地运行了
> > 谢谢提醒，本地运行就可以了，不知有以下提示有没影响的？
> > Close tag no opened match:[{"tag":"body","srcHtml":"","isClosing":false,"pos":0,"srcPos":0}]"h1"
> > Close tag no opened match:[{"tag":"body","srcHtml":"","isClosing":false,"pos":0,"srcPos":0}]"p"

这个属于原始书籍的问题，html代码不规范报的这个警告，应该不会影响内容阅读

**Comment by champkeh** [comment]
后续如果有epub的问题，在 #30 里面讨论
